#!/bin/sh

# so that FreeBSD runs it only once 
name=$1
key=$2
[ "$key" = "POST-DEINSTALL" ] && exit 0

[ -f /usr/local/etc/rc.d/npemwind ] && rm /usr/local/etc/rc.d/npemwind

cat <<EOF
To deinstall completely this package, the directories

/usr/local/etc/npemwin
/usr/local/share/doc/npemwin
/usr/local/libexec/npemwin
/var/npemwin

must be removed manually.
EOF
