#
# $Id$
#

set spoolfilter(conf)	     [file join $gf(confdir) "spoolfilter.conf"];
set spoolfilter(datadir)     [file join $gf(archivedatadir) "spool"];
set spoolfilter(datasubdir) "%Y%m%d";
#set spoolfilter(datasubdir) "%u";     # day of week (1-7)
set spoolfilter(uwildregex) {.*};

# Overrides in the configuration file.
if {[file exists $spoolfilter(conf)] == 1} {
    source $spoolfilter(conf);
}
